// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotesWebAPI.Db;

namespace QuotesWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200529101339_AddQuotes")]
    partial class AddQuotes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("QuotesWebAPI.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Dalai Lama",
                            InsertDate = new DateTime(2020, 5, 29, 15, 13, 39, 24, DateTimeKind.Local).AddTicks(3951),
                            Text = "The purpose of our lives is to be happy."
                        },
                        new
                        {
                            Id = 2,
                            Author = "John Lennon",
                            InsertDate = new DateTime(2020, 5, 29, 15, 13, 39, 26, DateTimeKind.Local).AddTicks(4052),
                            Text = "Life is what happens when you’re busy making other plans."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Stephen King",
                            InsertDate = new DateTime(2020, 5, 29, 15, 13, 39, 26, DateTimeKind.Local).AddTicks(4089),
                            Text = "Get busy living or get busy dying."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Mae West",
                            InsertDate = new DateTime(2020, 5, 29, 15, 13, 39, 26, DateTimeKind.Local).AddTicks(4091),
                            Text = "You only live once, but if you do it right, once is enough"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Babe Ruth",
                            InsertDate = new DateTime(2020, 5, 29, 15, 13, 39, 26, DateTimeKind.Local).AddTicks(4093),
                            Text = "Never let the fear of striking out keep you from playing the game"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
